const POPULAR_ICONS = [
  { slug: "google", title: "Google" },
  { slug: "github", title: "GitHub" },
  { slug: "gitlab", title: "GitLab" },
  { slug: "microsoft", title: "Microsoft" },
  { slug: "apple", title: "Apple" },
  { slug: "amazon", title: "Amazon" },
  { slug: "amazonwebservices", title: "AWS" },
  { slug: "facebook", title: "Facebook" },
  { slug: "instagram", title: "Instagram" },
  { slug: "twitter", title: "Twitter" },
  { slug: "x", title: "X" },
  { slug: "linkedin", title: "LinkedIn" },
  { slug: "youtube", title: "YouTube" },
  { slug: "reddit", title: "Reddit" },
  { slug: "spotify", title: "Spotify" },
  { slug: "slack", title: "Slack" },
  { slug: "discord", title: "Discord" },
  { slug: "telegram", title: "Telegram" },
  { slug: "whatsapp", title: "WhatsApp" },
  { slug: "signal", title: "Signal" },
  { slug: "tiktok", title: "TikTok" },
  { slug: "twitch", title: "Twitch" },
  { slug: "netflix", title: "Netflix" },
  { slug: "steam", title: "Steam" },
  { slug: "epicgames", title: "Epic Games" },
  { slug: "battle-dot-net", title: "Battle.net" },
  { slug: "nintendo", title: "Nintendo" },
  { slug: "xbox", title: "Xbox" },
  { slug: "playstation", title: "PlayStation" },
  { slug: "dropbox", title: "Dropbox" },
  { slug: "proton", title: "Proton" },
  { slug: "protonmail", title: "Proton Mail" },
  { slug: "bitwarden", title: "Bitwarden" },
  { slug: "1password", title: "1Password" },
  { slug: "lastpass", title: "LastPass" },
  { slug: "nordvpn", title: "NordVPN" },
  { slug: "paypal", title: "PayPal" },
  { slug: "stripe", title: "Stripe" },
  { slug: "shopify", title: "Shopify" },
  { slug: "binance", title: "Binance" },
  { slug: "coinbase", title: "Coinbase" },
  { slug: "kraken", title: "Kraken" },
  { slug: "docker", title: "Docker" },
  { slug: "kubernetes", title: "Kubernetes" },
  { slug: "terraform", title: "Terraform" },
  { slug: "cloudflare", title: "Cloudflare" },
  { slug: "digitalocean", title: "DigitalOcean" },
  { slug: "vercel", title: "Vercel" },
  { slug: "netlify", title: "Netlify" },
  { slug: "jenkins", title: "Jenkins" },
  { slug: "grafana", title: "Grafana" },
  { slug: "prometheus", title: "Prometheus" },
  { slug: "datadog", title: "Datadog" },
  { slug: "sentry", title: "Sentry" },
  { slug: "elastic", title: "Elastic" },
  { slug: "splunk", title: "Splunk" },
  { slug: "react", title: "React" },
  { slug: "vuedotjs", title: "Vue.js" },
  { slug: "angular", title: "Angular" },
  { slug: "svelte", title: "Svelte" },
  { slug: "nextdotjs", title: "Next.js" },
  { slug: "astro", title: "Astro" },
  { slug: "django", title: "Django" },
  { slug: "flask", title: "Flask" },
  { slug: "fastapi", title: "FastAPI" },
  { slug: "laravel", title: "Laravel" },
  { slug: "rubyonrails", title: "Rails" },
  { slug: "visualstudiocode", title: "VS Code" },
  { slug: "jetbrains", title: "JetBrains" },
  { slug: "notion", title: "Notion" },
  { slug: "obsidian", title: "Obsidian" },
  { slug: "figma", title: "Figma" },
  { slug: "canva", title: "Canva" },
  { slug: "adobe", title: "Adobe" },
  { slug: "zapier", title: "Zapier" },
  { slug: "linear", title: "Linear" },
  { slug: "evernote", title: "Evernote" },
  { slug: "todoist", title: "Todoist" },
  { slug: "trello", title: "Trello" },
  { slug: "jira", title: "Jira" },
  { slug: "atlassian", title: "Atlassian" },
  { slug: "airtable", title: "Airtable" },
  { slug: "zendesk", title: "Zendesk" },
  { slug: "intercom", title: "Intercom" },
  { slug: "hubspot", title: "HubSpot" },
  { slug: "salesforce", title: "Salesforce" },
  { slug: "wordpress", title: "WordPress" },
  { slug: "wix", title: "Wix" },
  { slug: "zoom", title: "Zoom" },
  { slug: "skype", title: "Skype" },
  { slug: "firefox", title: "Firefox" },
  { slug: "googlechrome", title: "Chrome" },
  { slug: "brave", title: "Brave" },
  { slug: "torproject", title: "Tor" },
  { slug: "ubuntu", title: "Ubuntu" },
  { slug: "debian", title: "Debian" },
  { slug: "fedora", title: "Fedora" },
  { slug: "archlinux", title: "Arch Linux" },
  { slug: "postgresql", title: "PostgreSQL" },
  { slug: "mysql", title: "MySQL" },
  { slug: "mongodb", title: "MongoDB" },
  { slug: "redis", title: "Redis" },
  { slug: "rabbitmq", title: "RabbitMQ" },
  { slug: "nginx", title: "Nginx" },
  { slug: "openai", title: "OpenAI" },
  { slug: "huggingface", title: "Hugging Face" },
  { slug: "tailwindcss", title: "Tailwind CSS" },
  { slug: "typescript", title: "TypeScript" },
  { slug: "javascript", title: "JavaScript" },
  { slug: "python", title: "Python" },
  { slug: "rust", title: "Rust" },
  { slug: "go", title: "Go" },
  { slug: "ruby", title: "Ruby" },
  { slug: "php", title: "PHP" },
  { slug: "swift", title: "Swift" },
  { slug: "kotlin", title: "Kotlin" },
  { slug: "graphql", title: "GraphQL" },
  { slug: "prisma", title: "Prisma" },
  { slug: "supabase", title: "Supabase" },
  { slug: "firebase", title: "Firebase" },
  { slug: "storybook", title: "Storybook" },
  { slug: "playwright", title: "Playwright" },
  { slug: "cypress", title: "Cypress" },
  { slug: "eslint", title: "ESLint" },
  { slug: "prettier", title: "Prettier" },
  { slug: "homeassistant", title: "Home Assistant" },
  { slug: "raspberrypi", title: "Raspberry Pi" },
  { slug: "arduino", title: "Arduino" },
  { slug: "bitcoin", title: "Bitcoin" },
  { slug: "ethereum", title: "Ethereum" },
  { slug: "solana", title: "Solana" },
  { slug: "monero", title: "Monero" },
  { slug: "litecoin", title: "Litecoin" },
  { slug: "dogecoin", title: "Dogecoin" },
  { slug: "polkadot", title: "Polkadot" },
  { slug: "chainlink", title: "Chainlink" },
  { slug: "alchemy", title: "Alchemy" },
  { slug: "metamask", title: "MetaMask" },
  { slug: "ledger", title: "Ledger" },
  { slug: "trezor", title: "Trezor" },
  { slug: "trustwallet", title: "Trust Wallet" },
  { slug: "exodus", title: "Exodus" },
  { slug: "bluehost", title: "Bluehost" },
  { slug: "hostinger", title: "Hostinger" },
  { slug: "godaddy", title: "GoDaddy" },
  { slug: "namecheap", title: "Namecheap" },
  { slug: "freenom", title: "Freenom" },
  { slug: "strapi", title: "Strapi" },
  { slug: "drupal", title: "Drupal" },
  { slug: "joomla", title: "Joomla" },
  { slug: "ghost", title: "Ghost" },
  { slug: "hugo", title: "Hugo" },
  { slug: "gatsby", title: "Gatsby" },
  { slug: "jekyll", title: "Jekyll" },
  { slug: "mdx", title: "MDX" },
  { slug: "vite", title: "Vite" },
  { slug: "webpack", title: "Webpack" },
  { slug: "esbuild", title: "esbuild" },
  { slug: "rollupdotjs", title: "Rollup" },
  { slug: "bun", title: "Bun" },
  { slug: "nodedotjs", title: "Node.js" },
  { slug: "deno", title: "Deno" },
  { slug: "pnpm", title: "pnpm" },
  { slug: "npm", title: "npm" },
  { slug: "yarn", title: "Yarn" },
  { slug: "git", title: "Git" },
  { slug: "bitbucket", title: "Bitbucket" },
  { slug: "gitea", title: "Gitea" },
  { slug: "codeberg", title: "Codeberg" },
  { slug: "stackoverflow", title: "Stack Overflow" },
  { slug: "mdnwebdocs", title: "MDN" },
  { slug: "wikipedia", title: "Wikipedia" },
  { slug: "hackerrank", title: "HackerRank" },
  { slug: "leetcode", title: "LeetCode" },
  { slug: "codepen", title: "CodePen" },
  { slug: "codesandbox", title: "CodeSandbox" },
  { slug: "replit", title: "Replit" },
  { slug: "glitch", title: "Glitch" },
  { slug: "hono", title: "Hono" },
  { slug: "express", title: "Express" },
  { slug: "fastify", title: "Fastify" },
  { slug: "nestjs", title: "NestJS" },
  { slug: "trpc", title: "tRPC" },
  { slug: "socketdotio", title: "Socket.io" },
  { slug: "axios", title: "Axios" },
  { slug: "swagger", title: "Swagger" },
  { slug: "postman", title: "Postman" },
  { slug: "insomnia", title: "Insomnia" },
  { slug: "tableau", title: "Tableau" },
  { slug: "powerbi", title: "Power BI" },
  { slug: "looker", title: "Looker" },
  { slug: "dbt", title: "dbt" },
  { slug: "snowflake", title: "Snowflake" },
  { slug: "databricks", title: "Databricks" },
  { slug: "apachespark", title: "Apache Spark" },
  { slug: "apachekafka", title: "Apache Kafka" },
  { slug: "confluent", title: "Confluent" },
  { slug: "apacheairflow", title: "Apache Airflow" },
  { slug: "prefect", title: "Prefect" },
  { slug: "dagster", title: "Dagster" },
  { slug: "temporal", title: "Temporal" },
  { slug: "pulumi", title: "Pulumi" },
  { slug: "ansible", title: "Ansible" },
  { slug: "puppet", title: "Puppet" },
  { slug: "chef", title: "Chef" },
  { slug: "saltproject", title: "Salt" },
  { slug: "circleci", title: "CircleCI" },
  { slug: "travisci", title: "Travis CI" },
  { slug: "drone", title: "Drone CI" },
  { slug: "buddy", title: "Buddy" },
  { slug: "teamcity", title: "TeamCity" },
  { slug: "bamboo", title: "Bamboo" },
  { slug: "argocd", title: "Argo CD" },
  { slug: "fluxcd", title: "Flux CD" },
  { slug: "tekton", title: "Tekton" },
  { slug: "helm", title: "Helm" },
  { slug: "rancher", title: "Rancher" },
  { slug: "openshift", title: "OpenShift" },
  { slug: "portainer", title: "Portainer" },
  { slug: "podman", title: "Podman" },
  { slug: "containerd", title: "containerd" },
  { slug: "k3s", title: "K3s" },
  { slug: "minikube", title: "minikube" },
  { slug: "kind", title: "kind" },
  { slug: "vagrant", title: "Vagrant" },
  { slug: "packer", title: "Packer" },
  { slug: "vault", title: "Vault" },
  { slug: "consul", title: "Consul" },
  { slug: "nomad", title: "Nomad" },
  { slug: "boundary", title: "Boundary" },
  { slug: "waypoint", title: "Waypoint" },
  { slug: "neon", title: "Neon" },
  { slug: "planetscale", title: "PlanetScale" },
  { slug: "turso", title: "Turso" },
  { slug: "railway", title: "Railway" },
  { slug: "flydotio", title: "Fly.io" },
  { slug: "render", title: "Render" },
  { slug: "heroku", title: "Heroku" },
  { slug: "coolify", title: "Coolify" },
  { slug: "dokku", title: "Dokku" },
  { slug: "caprover", title: "CapRover" },
  { slug: "linode", title: "Linode" },
  { slug: "vultr", title: "Vultr" },
  { slug: "ovh", title: "OVH" },
  { slug: "hetzner", title: "Hetzner" },
  { slug: "scaleway", title: "Scaleway" },
  { slug: "oracle", title: "Oracle" },
  { slug: "ibmcloud", title: "IBM Cloud" },
  { slug: "alibabacloud", title: "Alibaba Cloud" },
  { slug: "tencentcloud", title: "Tencent Cloud" },
  { slug: "baiducloud", title: "Baidu Cloud" },
  { slug: "gmail", title: "Gmail" },
  { slug: "outlook", title: "Outlook" },
  { slug: "yahoo", title: "Yahoo" },
  { slug: "tutanota", title: "Tutanota" },
  { slug: "fastmail", title: "Fastmail" },
  { slug: "thunderbird", title: "Thunderbird" },
  { slug: "mailgun", title: "Mailgun" },
  { slug: "sendgrid", title: "SendGrid" },
  { slug: "mailchimp", title: "Mailchimp" },
  { slug: "convertkit", title: "ConvertKit" },
  { slug: "substack", title: "Substack" },
  { slug: "medium", title: "Medium" },
  { slug: "devdotto", title: "DEV.to" },
  { slug: "hashnode", title: "Hashnode" },
  { slug: "mastodon", title: "Mastodon" },
  { slug: "bluesky", title: "Bluesky" },
  { slug: "threads", title: "Threads" },
  { slug: "slack", title: "Slack" },
  { slug: "teamspeak", title: "TeamSpeak" },
  { slug: "mumble", title: "Mumble" },
  { slug: "ventrilo", title: "Ventrilo" },
  { slug: "element", title: "Element" },
  { slug: "matrix", title: "Matrix" },
  { slug: "wire", title: "Wire" },
  { slug: "threema", title: "Threema" },
  { slug: "session", title: "Session" },
  { slug: "keybase", title: "Keybase" },
  { slug: "veracrypt", title: "VeraCrypt" },
  { slug: "keepassxc", title: "KeePassXC" },
  { slug: "gnupg", title: "GnuPG" },
  { slug: "yubico", title: "YubiKey" },
  { slug: "duckduckgo", title: "DuckDuckGo" },
  { slug: "startpage", title: "Startpage" },
  { slug: "searxng", title: "SearXNG" },
  { slug: "kagi", title: "Kagi" },
  { slug: "mullvad", title: "Mullvad" },
  { slug: "protonvpn", title: "Proton VPN" },
  { slug: "tailscale", title: "Tailscale" },
  { slug: "zerotier", title: "ZeroTier" },
  { slug: "wireguard", title: "WireGuard" },
  { slug: "openvpn", title: "OpenVPN" },
  { slug: "crowdsec", title: "CrowdSec" },
  { slug: "fail2ban", title: "Fail2Ban" },
  { slug: "pfSense", title: "pfSense" },
  { slug: "opnsense", title: "OPNsense" },
  { slug: "openwrt", title: "OpenWrt" },
  { slug: "ddwrt", title: "DD-WRT" },
  { slug: "proxmox", title: "Proxmox" },
  { slug: "vmware", title: "VMware" },
  { slug: "virtualbox", title: "VirtualBox" },
  { slug: "qemu", title: "QEMU" },
  { slug: "hyper", title: "Hyper" },
  { slug: "kitty", title: "Kitty" },
  { slug: "wezterm", title: "WezTerm" },
  { slug: "alacritty", title: "Alacritty" },
  { slug: "iterm2", title: "iTerm2" },
  { slug: "warp", title: "Warp" },
  { slug: "tmux", title: "tmux" },
  { slug: "fishshell", title: "Fish" },
  { slug: "zsh", title: "Zsh" },
  { slug: "ohmyzsh", title: "Oh My Zsh" },
  { slug: "starship", title: "Starship" },
  { slug: "neovim", title: "Neovim" },
  { slug: "emacs", title: "Emacs" },
  { slug: "helix", title: "Helix" },
  { slug: "zedindustries", title: "Zed" },
  { slug: "lapce", title: "Lapce" },
  { slug: "intellijidea", title: "IntelliJ IDEA" },
  { slug: "pycharm", title: "PyCharm" },
  { slug: "webstorm", title: "WebStorm" },
  { slug: "goland", title: "GoLand" },
  { slug: "clion", title: "CLion" },
  { slug: "rubymine", title: "RubyMine" },
  { slug: "phpstorm", title: "PhpStorm" },
  { slug: "datagrip", title: "DataGrip" },
  { slug: "rider", title: "Rider" },
  { slug: "fleet", title: "Fleet" },
  { slug: "androidstudio", title: "Android Studio" },
  { slug: "xcode", title: "Xcode" },
  { slug: "appstore", title: "App Store" },
  { slug: "googleplay", title: "Google Play" },
  { slug: "fdroid", title: "F-Droid" },
  { slug: "aurora", title: "Aurora Store" },
  { slug: "revanced", title: "ReVanced" },
  { slug: "newpipe", title: "NewPipe" },
  { slug: "libreoffice", title: "LibreOffice" },
  { slug: "onlyoffice", title: "OnlyOffice" },
  { slug: "openoffice", title: "Apache OpenOffice" },
  { slug: "googledocs", title: "Google Docs" },
  { slug: "googlesheets", title: "Google Sheets" },
  { slug: "googleslides", title: "Google Slides" },
  { slug: "googledrive", title: "Google Drive" },
  { slug: "onedrive", title: "OneDrive" },
  { slug: "terabox", title: "TeraBox" },
  { slug: "meganz", title: "MEGA" },
  { slug: "nextcloud", title: "Nextcloud" },
  { slug: "owncloud", title: "ownCloud" },
  { slug: "seafile", title: "Seafile" },
  { slug: "syncthing", title: "Syncthing" },
  { slug: "resilio", title: "Resilio Sync" },
  { slug: "calendly", title: "Calendly" },
  { slug: "clockify", title: "Clockify" },
  { slug: "toggl", title: "Toggl" },
  { slug: "rescuetime", title: "RescueTime" },
  { slug: "strava", title: "Strava" },
  { slug: "fitbit", title: "Fitbit" },
  { slug: "garmin", title: "Garmin" },
  { slug: "whoop", title: "Whoop" },
  { slug: "myfitnesspal", title: "MyFitnessPal" },
  { slug: "headspace", title: "Headspace" },
  { slug: "calm", title: "Calm" },
  { slug: "duolingo", title: "Duolingo" },
  { slug: "coursera", title: "Coursera" },
  { slug: "udemy", title: "Udemy" },
  { slug: "khanacademy", title: "Khan Academy" },
  { slug: "edx", title: "edX" },
  { slug: "pluralsight", title: "Pluralsight" },
  { slug: "egghead", title: "egghead.io" },
  { slug: "frontendmentor", title: "Frontend Mentor" },
  { slug: "codewars", title: "Codewars" },
  { slug: "exercism", title: "Exercism" },
  { slug: "freecodecamp", title: "freeCodeCamp" },
  { slug: "theodinproject", title: "The Odin Project" },
  { slug: "fullstackopen", title: "Full Stack Open" },
  { slug: "scrimba", title: "Scrimba" },
  { slug: "codecademy", title: "Codecademy" },
  { slug: "datacamp", title: "DataCamp" },
  { slug: "kaggle", title: "Kaggle" },
  { slug: "huggingface", title: "Hugging Face" },
  { slug: "huggingface", title: "Hugging Face" },
]

const titleMap: Record<string, string> = {}
for (const icon of POPULAR_ICONS) {
  if (!titleMap[icon.slug]) titleMap[icon.slug] = icon.title
}

export function getIconTitle(slug: string): string | undefined {
  return titleMap[slug]
}

export function getPopularIcons() {
  return POPULAR_ICONS
}

export function searchIcons(query: string, limit = 100) {
  if (!query || query.length < 2) return getPopularIcons().slice(0, limit)
  const q = query.toLowerCase()
  return POPULAR_ICONS
    .filter((i) => i.slug.includes(q) || i.title.toLowerCase().includes(q))
    .slice(0, limit)
}

export function getSimpleIconUrl(slug: string, title?: string): string {
  if (title && title !== slug) return `/api/icons/${slug}?name=${encodeURIComponent(title)}`
  return `/api/icons/${slug}`
}
